"""add_food_diary_models_clean

Revision ID: c2204f92a555
Revises: a1b2c3d4e5f6
Create Date: 2026-10-09 19:10:11.294723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2204f92a555'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_nutrition_summaries',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('summary_date', sa.Date(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fiber', sa.Float(), nullable=True),
    sa.Column('total_sugar', sa.Float(), nullable=True),
    sa.Column('water_intake_ml', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_daily_nutrition_summaries_summary_date'), 'daily_nutrition_summaries', ['summary_date'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_summaries_summary_id'), 'daily_nutrition_summaries', ['summary_id'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_summaries_user_id'), 'daily_nutrition_summaries', ['user_id'], unique=False)
    op.create_table('food_diary_entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(), nullable=True),
    sa.Column('meal_category', sa.String(), nullable=True),
    sa.Column('quantity_consumed', sa.Float(), nullable=True),
    sa.Column('serving_unit', sa.String(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('carbohydrates', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('consumption_date', sa.Date(), nullable=True),
    sa.Column('consumption_time', sa.String(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_food_diary_entries_consumption_date'), 'food_diary_entries', ['consumption_date'], unique=False)
    op.create_index(op.f('ix_food_diary_entries_entry_id'), 'food_diary_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_food_diary_entries_user_id'), 'food_diary_entries', ['user_id'], unique=False)
    op.create_table('food_symptom_associations',
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('food_name_or_ingredient', sa.String(), nullable=True),
    sa.Column('associated_symptom', sa.String(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('clinical_recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('association_id')
    )
    op.create_index(op.f('ix_food_symptom_associations_association_id'), 'food_symptom_associations', ['association_id'], unique=False)
    op.create_index(op.f('ix_food_symptom_associations_user_id'), 'food_symptom_associations', ['user_id'], unique=False)
    op.create_table('meal_recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_category', sa.String(), nullable=True),
    sa.Column('suggested_food', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('nutrition_estimate_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_meal_recommendations_recommendation_id'), 'meal_recommendations', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_meal_recommendations_user_id'), 'meal_recommendations', ['user_id'], unique=False)
    # op.create_unique_constraint(None, 'patient_medical_profiles', ['user_id'])
    # op.create_index_medication_id'), 'patient_medications', ['medication_id'], unique=False)
    # op.create_index_symptom_id'), 'symptom_entries', ['symptom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symptom_entries_symptom_id'), table_name='symptom_entries')
    op.drop_index(op.f('ix_patient_medications_medication_id'), table_name='patient_medications')
    # op.drop_constraint(None, 'patient_medical_profiles', type_='unique')
    op.drop_index(op.f('ix_meal_recommendations_user_id'), table_name='meal_recommendations')
    op.drop_index(op.f('ix_meal_recommendations_recommendation_id'), table_name='meal_recommendations')
    op.drop_table('meal_recommendations')
    op.drop_index(op.f('ix_food_symptom_associations_user_id'), table_name='food_symptom_associations')
    op.drop_index(op.f('ix_food_symptom_associations_association_id'), table_name='food_symptom_associations')
    op.drop_table('food_symptom_associations')
    op.drop_index(op.f('ix_food_diary_entries_user_id'), table_name='food_diary_entries')
    op.drop_index(op.f('ix_food_diary_entries_entry_id'), table_name='food_diary_entries')
    op.drop_index(op.f('ix_food_diary_entries_consumption_date'), table_name='food_diary_entries')
    op.drop_table('food_diary_entries')
    op.drop_index(op.f('ix_daily_nutrition_summaries_user_id'), table_name='daily_nutrition_summaries')
    op.drop_index(op.f('ix_daily_nutrition_summaries_summary_id'), table_name='daily_nutrition_summaries')
    op.drop_index(op.f('ix_daily_nutrition_summaries_summary_date'), table_name='daily_nutrition_summaries')
    op.drop_table('daily_nutrition_summaries')
    # ### end Alembic commands ###

