"""Add raw_ocr_text to receipt

Revision ID: f08beec4c3ae
Revises: bee9ff9322a4
Create Date: 2026-09-08 16:35:33.402013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08beec4c3ae'
down_revision: Union[str, Sequence[str], None] = 'bee9ff9322a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('raw_ocr_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'raw_ocr_text')
    # ### end Alembic commands ###
